<?php

namespace greevex\gss\translator;

use greevex\gss\lib\error;

/**
 * @author greevex
 * @date: 10/1/14 6:10 PM
 */

class gsphp
{
    private $structure;
    private $content = '%initialize%';

    public function __construct($structure)
    {
        $this->structure = $structure;
    }

    public function process()
    {

    }

    protected function putToPointer($pointer, $content)
    {
        $pointer = "%{$pointer}%";
        if(strpos($this->content, $pointer) === false) {
            error::throwNewCompileException("Unable to find pointer {$pointer}", 0, 0);
        }
        $this->content = str_replace($pointer, $content, $this->content);
    }

    protected function initialize()
    {
        $namespace = helper::dotPathToNamespace($this->structure['package']);
        $packageData = helper::splitNamespaceAndClass($namespace);
        $generator = __CLASS__;
        $date = date("Y-m-d H:i:s");
        $base = <<<PHP
namespace {$packageData['namespace']};

/**
 * This file is generated by GsPHP
 *
 * @generator {$generator}
 * @date {$date}
 */
class {$packageData['class']}
{
%class_content%
}
PHP;
        $this->putToPointer('initialize', $base);
    }
}